package game;

public enum Field {
    EMPTY, ROOK_WHITE, BISSHOP_WHITE, KNIGHT_WHITE, QUEEN_WHITE, KING_WHITE, PAWN_WHITE, ROOK_BLACK, BISSHOP_BLACK, KNIGHT_BLACK, QUEEN_BLACK, KING_BLACK, PAWN_BLACK
}
